import { Vazirmatn } from "next/font/google";

import "./globals.css";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
});

export const metadata = {
  title: "Information",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${vazirmatn.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
